import type { Ideia } from './tipos';

// Dados fictícios só para o protótipo (nomes e ideias inventados).
const agora = Date.now();
const hora = 3600_000;
const dia = 24 * hora;
const ha = (ms: number) => new Date(agora - ms).toISOString();

export const utilizadorAtual = { nome: 'Nuno', nomeCompleto: 'Nuno Peixoto', empresa: 'dstelecom, s.a.' };

export const ideiasExemplo: Ideia[] = [
  {
    num: 3036,
    titulo: 'Informação de Recrutamento',
    tipo: 'melhoria',
    descricao:
      'Uma empresa da concorrência usa uma forma de publicidade que pode ser útil para divulgarmos as vagas de emprego do grupo.',
    autores: ['Ricardo Lopes'],
    anonima: false,
    privada: false,
    data: ha(3 * dia),
    estado: 'em-discussao',
    likes: 2,
    gostei: false,
    anexos: ['RECRUTAMENTO.jpg'],
    comentarios: [
      {
        id: 1,
        autor: 'Marta Sousa',
        empresa: 'fiber t, s.a.',
        texto: 'Excelente ideia, sugeria até incluir um QR code para facilitar o acesso ao site de recrutamento do grupo.',
        data: ha(2 * hora),
        gostos: 0,
        gostei: false,
      },
    ],
  },
  {
    num: 3035,
    titulo: 'Academia SAP',
    tipo: 'simples',
    descricao: 'Criar um percurso de formação interna em SAP para novos colaboradores das áreas administrativas.',
    autores: ['Carla Ferreira'],
    anonima: false,
    privada: false,
    data: ha(8 * dia),
    estado: 'em-discussao',
    likes: 3,
    gostei: false,
    anexos: [],
    comentarios: [
      { id: 2, autor: 'Paulo Mendes', empresa: 'dstelecom, s.a.', texto: 'Seria muito útil para quem entra no grupo.', data: ha(5 * dia), gostos: 1, gostei: false },
    ],
  },
  {
    num: 3034,
    titulo: 'Gestão partilhada dos carregamentos de veículos elétricos',
    tipo: 'melhoria',
    descricao: 'Uma aplicação simples para reservar os postos de carregamento do parque e evitar carros parados depois de carregados.',
    autores: ['Inês Correia'],
    anonima: false,
    privada: false,
    data: ha(8 * dia),
    estado: 'em-discussao',
    likes: 3,
    gostei: false,
    anexos: [],
    comentarios: [],
  },
  {
    num: 3031,
    titulo: 'Sugestão de melhoria de espaço - Copa',
    tipo: 'melhoria',
    descricao: 'Reorganizar a copa do piso 1 com mais lugares sentados e uma zona para refeições rápidas.',
    autores: [],
    anonima: true,
    privada: false,
    data: ha(15 * dia),
    estado: 'em-discussao',
    likes: 7,
    gostei: false,
    anexos: [],
    comentarios: [],
  },
  {
    num: 3030,
    titulo: 'Oferta de bilhetes de museu no aniversário do colaborador',
    tipo: 'melhoria',
    descricao: 'Oferecer a cada colaborador um bilhete para um museu da cidade no dia do aniversário.',
    autores: ['Joana Ribeiro'],
    anonima: false,
    privada: false,
    data: ha(15 * dia),
    estado: 'em-discussao',
    likes: 38,
    gostei: true,
    anexos: [],
    comentarios: [
      { id: 3, autor: 'Hugo Matos', empresa: 'dstgroup', texto: 'Ótima forma de valorizar as pessoas.', data: ha(10 * dia), gostos: 4, gostei: false },
      { id: 4, autor: 'Sara Nogueira', empresa: 'fiber t, s.a.', texto: 'Podia incluir também um acompanhante.', data: ha(9 * dia), gostos: 2, gostei: false },
    ],
  },
  {
    num: 3029,
    titulo: 'Alteração das condições de pagamento especiais',
    tipo: 'detalhado',
    descricao: 'Rever as condições de pagamento especiais a fornecedores pequenos para reduzir o tempo médio de pagamento.',
    autores: ['Paula Teixeira'],
    anonima: false,
    privada: false,
    data: ha(15 * dia),
    estado: 'em-discussao',
    likes: 14,
    gostei: false,
    anexos: [],
    comentarios: [],
    modeloNegocio: 'Sem receita direta; reduz custos de financiamento dos fornecedores parceiros.',
    custos: 'Sem custos de implementação.',
  },
  {
    num: 3021,
    titulo: 'Sensores de ocupação nas salas de reunião',
    tipo: 'detalhado',
    descricao: 'Sensores simples que mostram no calendário se a sala está mesmo ocupada.',
    autores: ['Tiago Araújo'],
    anonima: false,
    privada: false,
    data: ha(40 * dia),
    estado: 'em-avaliacao',
    likes: 21,
    gostei: false,
    anexos: [],
    comentarios: [],
    responsabilidade: 'dstelecom',
  },
  {
    num: 3018,
    titulo: 'Kit de boas-vindas digital',
    tipo: 'melhoria',
    descricao: 'Substituir o manual impresso de acolhimento por um kit digital com vídeos curtos.',
    autores: ['Beatriz Pinto'],
    anonima: false,
    privada: false,
    data: ha(45 * dia),
    estado: 'em-avaliacao',
    likes: 9,
    gostei: false,
    anexos: [],
    comentarios: [],
    responsabilidade: 'dst',
  },
  {
    num: 3012,
    titulo: 'Manutenção preditiva das OLT com IA',
    tipo: 'detalhado',
    descricao: 'Usar os registos dos equipamentos para prever falhas antes de afetarem os clientes.',
    autores: ['André Costa', 'Rui Faria'],
    anonima: false,
    privada: false,
    data: ha(70 * dia),
    estado: 'aprovada',
    likes: 25,
    gostei: false,
    anexos: [],
    comentarios: [],
    responsabilidade: 'dstelecom',
    notas: { custo: 2, enquadramento: 3, beneficio: 3, adequacao: 3, incerteza: 2 },
    classe: 'projeto',
  },
  {
    num: 3008,
    titulo: 'Bebedouros nas obras',
    tipo: 'melhoria',
    descricao: 'Instalar bebedouros portáteis nas frentes de obra no verão.',
    autores: ['Luís Gomes'],
    anonima: false,
    privada: false,
    data: ha(80 * dia),
    estado: 'nao-aprovada',
    likes: 6,
    gostei: false,
    anexos: [],
    comentarios: [],
    responsabilidade: 'dstelecom',
    notas: { custo: 0, enquadramento: 0, beneficio: 0, adequacao: 0, incerteza: 0 },
    classe: 'duplicada',
  },
];
