# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:7240

# POST Users Login (cookie)
# Utilizador de desenvolvimento criado no arranque (ApplicationDbContextInitialiser).
POST {{Web_HostAddress}}/api/Users/login?useCookies=true
Content-Type: application/json

{
  "email": "administrator@localhost",
  "password": "Administrator1!"
}

###

# GET Users Info (utilizador autenticado)
GET {{Web_HostAddress}}/api/Users/manage/info

###
